version: 2
updates:
  # Enable version updates for npm (pnpm)
  - package-ecosystem: "npm"
    directory: "/pns-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "pnpm"
      include: "scope"
    reviewers:
      - "dependabot"
    assignees:
      - "dependabot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # Add pnpm-specific configuration
    package-manager: "npm"
    update-schedule: "weekly"
    target-branch: "main"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "dependabot"
    assignees:
      - "dependabot"

# Enable security updates
security-updates:
  enabled: true
  schedule:
    interval: "daily"
  open-pull-requests-limit: 2
  labels:
    - "security"
    - "dependencies"
